name: update-schema
on:
  workflow_dispatch: {
    inputs:
      schemaVersion:
        default: ""
        description: version of the schema to target
        required: false
  }
  schedule:
    - cron: '16 * * * *'
jobs:
  update-schema:
    runs-on: ubuntu-18.04
    steps:
      - name set schema version
        if: github.event_name == 'repository_dispatch'
        run: echo '::set-env name=TARGET_SCHEMA_VERSION::${{ github.event.inputs.schemaVersion }}'
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - run: script/new-schema-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
